# Generated by Django 2.0.7 on 2018-07-25 08:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('info', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_number', models.IntegerField(blank=True)),
                ('description', models.CharField(blank=True, max_length=30)),
                ('car_number', models.CharField(max_length=9)),
                ('booking_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking_duration', models.IntegerField(default=40)),
                ('place_type', models.IntegerField(default=1)),
                ('state', models.PositiveSmallIntegerField(default=1)),
                ('comment', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('letter', models.CharField(max_length=2)),
                ('info', models.CharField(max_length=100)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.Enterprise')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.Zone'),
        ),
    ]
