# Generated by Django 2.0.7 on 2018-07-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
