# Generated by Django 2.0.7 on 2018-07-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='place',
            name='parent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='place',
            name='booking_created',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='booking_start',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='car_number',
            field=models.CharField(default=None, max_length=9),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
