# Generated by Django 2.0.7 on 2018-07-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_auto_20180726_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='state',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
