# Generated by Django 2.0.7 on 2018-07-25 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_place_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='booking_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='place',
            name='booking_start',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='place',
            name='car_number',
            field=models.CharField(default=None, max_length=9),
        ),
    ]
