# Generated by Django 2.0.7 on 2018-07-25 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_auto_20180725_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='booking_start',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 25, 17, 24, 34)),
        ),
    ]
