# Generated by Django 2.0.7 on 2018-07-25 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_auto_20180725_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='booking_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 25, 17, 27, 33)),
        ),
        migrations.AlterField(
            model_name='place',
            name='booking_start',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 25, 17, 27, 33)),
        ),
    ]
