# Generated by Django 2.0.7 on 2018-07-25 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_auto_20180725_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='place',
            name='booking_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 25, 17, 46, 45)),
        ),
        migrations.AlterField(
            model_name='place',
            name='booking_start',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 25, 17, 46, 45)),
        ),
    ]
