# Generated by Django 2.0.7 on 2018-07-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_auto_20180725_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='booking_created',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='booking_start',
            field=models.DateTimeField(blank=True),
        ),
    ]
